// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB372ScWAGZFbRpYA8g8sMDO0vV6CKKsL8',
    appId: '1:739721869191:web:cd05852a2ecd8281538522',
    messagingSenderId: '739721869191',
    projectId: 'testprojet-acf85',
    authDomain: 'testprojet-acf85.firebaseapp.com',
    databaseURL: 'https://testprojet-acf85-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testprojet-acf85.appspot.com',
    measurementId: 'G-T8LTVW75KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYurXe_VcdorN49ATiZWzPLJcTJdRLH_Y',
    appId: '1:739721869191:android:2bcf97278e65937c538522',
    messagingSenderId: '739721869191',
    projectId: 'testprojet-acf85',
    databaseURL: 'https://testprojet-acf85-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testprojet-acf85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA56748q-6MjmYP0mdrKDh6ggpXYut3MuQ',
    appId: '1:739721869191:ios:b6eed41747fed59d538522',
    messagingSenderId: '739721869191',
    projectId: 'testprojet-acf85',
    databaseURL: 'https://testprojet-acf85-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testprojet-acf85.appspot.com',
    iosBundleId: 'com.daphane.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA56748q-6MjmYP0mdrKDh6ggpXYut3MuQ',
    appId: '1:739721869191:ios:566fab23b7a3d83d538522',
    messagingSenderId: '739721869191',
    projectId: 'testprojet-acf85',
    databaseURL: 'https://testprojet-acf85-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testprojet-acf85.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB372ScWAGZFbRpYA8g8sMDO0vV6CKKsL8',
    appId: '1:739721869191:web:77e0c40dd46e796e538522',
    messagingSenderId: '739721869191',
    projectId: 'testprojet-acf85',
    authDomain: 'testprojet-acf85.firebaseapp.com',
    databaseURL: 'https://testprojet-acf85-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testprojet-acf85.appspot.com',
    measurementId: 'G-D18LZ4NG73',
  );

}