name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  google_fonts: ^6.2.1
  transparent_image: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/image0.jpg
    - assets/images/image1.png
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.webp

